### ISSUE TITLE
xingX 计算时数据错误，应该是X0_DATA排版造成了数据丢失

### ISSUE THREAD

**Issue by mm-longcheng** [sxwnl/sxwnl-cpp#1]
很高兴你能分享这么好的仓库，sxwnl是一个很不错的工具。不过我在使用中发现了一点小问题。

我在使用原版sxwnl和这个cpp版本测试时，使用以下参数调用
xingX 函数

    Date date = { 2008, 1, 1, 16, 01, 06, };
    double jd1 = toJD(date);
    std::string ss = xingX(1, jd1, 116.383333, 39.900000);

得出来的结果
黄经一  118°45'17.90" 黄纬一 -  1°14'03.64" 向径一 0.34029803
视黄经  319°17'50.58" 视黄纬 -  0°00'52.81" 地心距 30.75000331
视赤经   21h26m17.35s 视赤纬 - 14°35'51.62" 光行距 30.75109687
站赤经   21h26m17.35s 站赤纬 - 14°35'51.44" 视距离 30.75031741
方位角  347°33'00.93" 高度角 - 50°10'28.08"
恒星时    8h20m23.88s(平)    8h20m22.98s(真)

原版本结果
黄经一  118°45'17.90" 黄纬一 -  1°14'03.64" 向径一 0.34029803
视黄经  329°11'41.25" 视黄纬 -  0°36'36.18" 地心距 0.68949784
视赤经   22h 05m35.98s 视赤纬 - 11°58'42.55" 光行距 0.68954181
站赤经   22h 05m36.14s 站赤纬 - 11°58'34.00" 视距离 0.68953082
方位角  334°18'18.13" 高度角 - 45°42'15.21"
恒星时    8h 20m23.86s(平)    8h 20m22.96s(真)

经过追踪发现，xingX在进行第一个
a = p_coord(0, T, -1, -1, -1); //地球
里面的第三轮
z[2] = XL0_calc(xt, 2, t, n3);

		v	9911640062.2808208	double
		v	9980396185.0125237	double
		v	9982116433.6923618	double
		v	310683183916.42719	double  cpp 版本在第四个循环会出现异常值
		v	9911640062.2808208	double  原版数据是这个

在这轮循环里我特别查看了 F[j] F[j + 1] F[j + 2]的数据
cpp 版 值分别为 
		F[j]       1.00000000e+09	float     这连续的三个值，明显索引到了 X1_DATA 中的前三个数据
		F[j + 1] 20.0000000	float
		F[j + 2] 443.000000	float
原版为 
		F[j]       14459.0000	float             这三个连续数值，索引到了X0  /*R3*/  14459,4.27319,6283.07585,  
		F[j + 1] 4.27319002	float
		F[j + 2] 6283.07568	float

我对比两份数据文件发现了一些端倪，在X0_DATA /*R2*/ 这行数据的最后是这样的  5.36,25158.60,/\   
注意最后的两个斜杠，末尾的反斜杠应该是宏定义的换行，但是前面多出了一个斜杠，可能这个斜杠照成了后面的数据被丢弃了。

**Comment by qaiu** [comment]
太久没来这个项目了, 不过还是感谢指正, 已修复

**Comment by qaiu** [comment]
> 很高兴你能分享这么好的仓库，sxwnl是一个很不错的工具。不过我在使用中发现了一点小问题。
> 
> 我在使用原版sxwnl和这个cpp版本测试时，使用以下参数调用
> xingX 函数
> 
>     Date date = { 2008, 1, 1, 16, 01, 06, };
>     double jd1 = toJD(date);
>     std::string ss = xingX(1, jd1, 116.383333, 39.900000);
> 
> 得出来的结果
> 黄经一  118°45'17.90" 黄纬一 -  1°14'03.64" 向径一 0.34029803
> 视黄经  319°17'50.58" 视黄纬 -  0°00'52.81" 地心距 30.75000331
> 视赤经   21h26m17.35s 视赤纬 - 14°35'51.62" 光行距 30.75109687
> 站赤经   21h26m17.35s 站赤纬 - 14°35'51.44" 视距离 30.75031741
> 方位角  347°33'00.93" 高度角 - 50°10'28.08"
> 恒星时    8h20m23.88s(平)    8h20m22.98s(真)
> 
> 原版本结果
> 黄经一  118°45'17.90" 黄纬一 -  1°14'03.64" 向径一 0.34029803
> 视黄经  329°11'41.25" 视黄纬 -  0°36'36.18" 地心距 0.68949784
> 视赤经   22h 05m35.98s 视赤纬 - 11°58'42.55" 光行距 0.68954181
> 站赤经   22h 05m36.14s 站赤纬 - 11°58'34.00" 视距离 0.68953082
> 方位角  334°18'18.13" 高度角 - 45°42'15.21"
> 恒星时    8h 20m23.86s(平)    8h 20m22.96s(真)
> 
> 经过追踪发现，xingX在进行第一个
> a = p_coord(0, T, -1, -1, -1); //地球
> 里面的第三轮
> z[2] = XL0_calc(xt, 2, t, n3);
> 
> 		v	9911640062.2808208	double
> 		v	9980396185.0125237	double
> 		v	9982116433.6923618	double
> 		v	310683183916.42719	double  cpp 版本在第四个循环会出现异常值
> 		v	9911640062.2808208	double  原版数据是这个
> 
> 在这轮循环里我特别查看了 F[j] F[j + 1] F[j + 2]的数据
> cpp 版 值分别为 
> 		F[j]       1.00000000e+09	float     这连续的三个值，明显索引到了 X1_DATA 中的前三个数据
> 		F[j + 1] 20.0000000	float
> 		F[j + 2] 443.000000	float
> 原版为 
> 		F[j]       14459.0000	float             这三个连续数值，索引到了X0  /*R3*/  14459,4.27319,6283.07585,  
> 		F[j + 1] 4.27319002	float
> 		F[j + 2] 6283.07568	float
> 
> 我对比两份数据文件发现了一些端倪，在X0_DATA /*R2*/ 这行数据的最后是这样的  5.36,25158.60,/\   
> 注意最后的两个斜杠，末尾的反斜杠应该是宏定义的换行，但是前面多出了一个斜杠，可能这个斜杠照成了后面的数据被丢弃了。

有点奇怪，你调用这个函数地理位置为什么没有转为弧度，原版默认会转为弧度，得到原版结果 难道直接运行的js代码么？

**Comment by mm-longcheng** [comment]
什么弧度？你说的是经纬度是吧116.383333, 39.900000。它们现在的单位没问题。我是直接将js里的调用点输入参数打印出来，然后将其作为参数传给c++版本，做的对比测试。js版你打开星历选水星，就是那里。

**Comment by qaiu** [comment]
> 什么弧度？你说的是经纬度是吧116.383333, 39.900000。它们现在的单位没问题。我是直接将js里的调用点输入参数打印出来，然后将其作为参数传给c++版本，做的对比测试。js版你打开星历选水星，就是那里。

Date date = { 2008, 1, 1, 16, 01, 06, };
double jd1 = toJD(date);
std::string ss = xingX(1, jd1, 116.383333, 39.900000);

得到的结果和js版里输入相同参数并不一致
1. jd1需要转为jd2000相对时间所以需要 toJD(date) - J2000;
2. xingX函数接收的坐标是弧度坐标需要 度数 / 180 * M_PI转一下

完整写法：
```cpp
#define A2R(x) ((x) / 180 * M_PI)

  Date date = { 2008, 1, 1, 0, 0, 0};
  double jd1 = toJD(date) - J2000;;
  std::string ss = xingX(1, jd1, A2R(116.383333), A2R(39.900000));


```

**Comment by mm-longcheng** [comment]
首先修改js代码，在输出结果的字符串后面，末尾附加上传入这个函数的参数，然后你用浏览器打开js版本的sxwnl，就可以直观看到输入参数。然后传给需要验证的移植版做单元测试。

**Comment by mm-longcheng** [comment]
index.htm里面572行
s += xingX(xt,jd,L,fa)+'\r\n';
换成类似这样
s += xingX(xt,jd,L,fa) + '  '  +xt+ '  ' +jd + '  '  +L + '  '  +fa + '  '  +'\r\n';
我是直接做的函数的单元测试。

当时可能是将c++版本的传入参数写死在js里面做的单元测试。总之是两函数参数保证一致测试的。你也可以自己验证一下问题。

**Comment by qaiu** [comment]
这样测试的确可以，能发现问题，
不过对于网页里输入这些参数，它实际上还有进一步的处理，所以在网页里输入这些参数得到的结果和单元测试并不一致，emmm，我本来不改去网页里尝试输入这些参数的😂后来才发现单位需要换算的

距离当初翻译这个程序已经过去好多年了，当时水平有限，代码也显得业余，也埋了不少坑，后来也时间了处理，现在来看要完善的地方还有很多很多，慢慢来吧

**Comment by mm-longcheng** [comment]
我这么写就是做单元测试用的，我知道它对参数有预处理。我自己也复刻了一份c语言的实现，所以只是顺带也做了你这个版本的单元测试，我发现的几个问题应该都已经提给你了。

**Comment by qaiu** [comment]
挺感谢的，请问你做的C语言版实现开源了吗，想观摩一下

**Comment by mm-longcheng** [comment]
用纯c实现一套系统比起c++，需要自己实现stl和字符串等等轮子，所以我的版本是依附于我的自有组件体系，并不是一个单独的仓库。
仓库目录地址
https://bitbucket.org/mm_longcheng/mm-core/src/dev/dish/src/sxwnl/
这是最近做的一份vulkan渲染接口安卓版本的日历
https://share.weiyun.com/upjUrFv8

**Comment by qaiu** [comment]
挺好![Screenshot_2022-08-13-22-06-14-103_org.mm.nwsi.vkApp.jpg](https://user-images.githubusercontent.com/29825328/184497783-ac181a69-ad52-41db-a8cb-4fbe27b1791e.jpg)
