### ISSUE TITLE
X0_DATA 数据排版造成数据丢失

### ISSUE THREAD

**Issue by mm-longcheng** [sxwnl/sxwnl-cpp#2]
我在使用xingX函数发现结果和原版不一样

    Date date = { 2008, 1, 1, 16, 01, 06, };
    double jd1 = toJD(date);
    std::string ss = xingX(1, jd1, 116.383333, 39.900000);

cpp版本结果
黄经一  118°45'17.90" 黄纬一 -  1°14'03.64" 向径一 0.34029803
视黄经  319°17'50.58" 视黄纬 -  0°00'52.81" 地心距 30.75000331
视赤经   21h26m17.35s 视赤纬 - 14°35'51.62" 光行距 30.75109687
站赤经   21h26m17.35s 站赤纬 - 14°35'51.44" 视距离 30.75031741
方位角  347°33'00.93" 高度角 - 50°10'28.08"
恒星时    8h20m23.88s(平)    8h20m22.98s(真)

原版结果
黄经一  118°45'17.90" 黄纬一 -  1°14'03.64" 向径一 0.34029803
视黄经  329°11'41.25" 视黄纬 -  0°36'36.18" 地心距 0.68949784
视赤经   22h 05m35.98s 视赤纬 - 11°58'42.55" 光行距 0.68954181
站赤经   22h 05m36.14s 站赤纬 - 11°58'34.00" 视距离 0.68953082
方位角  334°18'18.13" 高度角 - 45°42'15.21"
恒星时    8h 20m23.86s(平)    8h 20m22.96s(真)

对比和跟踪发现
可能是 X0_DATA 数据排版造成数据丢失
通过对比我发现X0_DATA的/*R2*/ 行数据末尾 5.36,25158.60,/\ 有两个斜杠，前面那个正斜杠可能是后面的数据丢失了

z[2] = XL0_calc(xt, 2, t, n3);
a = p_coord(0, T,-1,-1,-1); //地球

里面的第四轮循环出现数据异常
		v	9911640062.2808208	double
		v	9980396185.0125237	double
		v	9982116433.6923618	double
		v	310683183916.42719	double  这个是cpp版本的数据

		v	9977739110.1463089	double  这个是原版数据

我查看了F[j] F[j + 1] F[j + 2]
cpp 版本是
F[j]        v0	1.00000000e+09	float     这三个数据其实是索引到了 X1_DATA 的前三位
F[j+1]   v1	20.0000000	float
F[j+2]   v2	443.000000	float

原始版本是
F[j]        v0	14459.0000	float             原始版本则是正确索引到X0_DATA/*R3*/  14459,4.27319,6283.07585,
F[j+1]   v1	4.27319002	float
F[j+2]   v2	6283.07568	float

**Comment by mm-longcheng** [comment]
这个可以直接关掉了，由于提交issue的时候github卡住了，导致我不得不重新提交了一次，没想到第一次也提交成功了。

**Comment by qaiu** [comment]
OK
