### ISSUE TITLE
SZJ calcRTS sq 现在是int类型，应该改成double

### ISSUE THREAD

**Issue by mm-longcheng** [sxwnl/sxwnl-cpp#3]
jd = 8200, vJ = 2.031272361112734, vW = 0.6963863715457375, tz = -8
SZJ::calcRTS(jd, 1, vJ, vW, tz);

function RTS1(jd,vJ,vW,tz){
 sq = SZJ.calcRTS(jd, 1, vJ, vW, tz); //升降计算,使用北时时间,tz=-8指东8区,jd+tz应在当地正午左右(误差数小时不要紧)
 var s, ob = SZJ.rts[0];
// JD.setFromJD(jd+J2000);
 s  = '日出 <font color=red>'+ob.s + '</font> 日落 '+ob.j +' 中天 '+ob.z +'<br>';
 s += '月出 '+ob.Ms+ ' 月落 '+ob.Mj+' 月中 '+ob.Mz+'<br>';
 s += '晨起天亮 '+ob.c + ' 晚上天黑 '+ob.h +'<br>';
 s += '日照时间 '+ob.sj+ ' 白天时间 '+ob.ch+'<br>';
 s += jd + " " + vJ + " " + vW + " " + tz + " " + sq;
 return s;
}

得出的结果是
        //日出 20:45:22 日落 11:44:10 中天 04:14:42
        //月出 11:51:31 月落 20:58:21 月中 16:26:18
        //晨起天亮 20:12:40 晚上天黑 12:16:53
        //日照时间 14:58:48 白天时间 16:04:12
        //csEphSZJ_RTS1_(8200, 2.031272361112734, 0.6963863715457375, -8, &s);

原版是
日出 04:45:22 日落 19:44:10 中天 12:14:42
月出 19:51:31 月落 04:03:28 月中 --:--:--
晨起天亮 04:12:40 晚上天黑 20:16:53
日照时间 14:58:48 白天时间 16:04:12

我跟踪打印了sq发现SZJ.calcRTS(jd, 1, vJ, vW, tz)这个函数里面sq等于-0.3333333333333333并不是整形。

**Comment by mm-longcheng** [comment]
我看你别的issue回复了一部分，这个却没有。我再描述清楚一些比较好。
void SZJ::calcRTS(double jd, int n, double Jdl, double Wdl, int sq)
里面最后一个参数int sq，根据我实际单元测试和与原版js计算结果对比应该是double sq.

**Comment by qaiu** [comment]
已修改
