### ISSUE TITLE
void rsPL::zb0(double jd) 里 double E=hcjj(jd/365251.0); 后面参数应该是错的

### ISSUE THREAD

**Issue by mm-longcheng** [sxwnl/sxwnl-cpp#5]
js 原版
 zb0:function(jd){
  //基本参数计算
  var deltat = dt_T(jd); //TD-UT
  var E=hcjj(jd/36525);
  var zd=nutation2(jd/36525);

应该直接就是36525，因为jd是double，所以也可以后面不加.0

**Comment by qaiu** [comment]
不影响计算
