### ISSUE TITLE
void rsPL::secMax 这个函数和js原版好像有很大的逻辑不一致

### ISSUE THREAD

**Issue by mm-longcheng** [sxwnl/sxwnl-cpp#6]
//求直线到太阳中心的最小值
  double x=G.x+dt2*v, y=G.y+dt2*u, rmin=sqrt(x*x+y*y);

  if(rmin<=G.mr+G.sr)
  { //偏食计算
   rsPL::sT[1] = jd; //食甚
   rsPL::LX="偏";
   rsPL::sf=(G.mr+G.sr-rmin)/G.sr/2.0; //食分
   rsPL::b1=G.mr/G.sr;

js 原版这里往后多了很多逻辑
  //求直线到太阳中心的最小值
  var maxsf = 0, maxjd = jd, rmin, ls;
  for (i = -30; i < 30; i += 6) {
   tt = jd + i / 86400;
   this.secXY(tt, L, fa, high, g);
   ls = (g.mr + g.sr - Math.sqrt(g.x * g.x + g.y * g.y)) / g.sr / 2;
   if (ls > maxsf) maxsf = ls, maxjd = tt;
  }
  jd = maxjd;
  for (i = -5; i < 5; i += 1) {
   tt = jd + i / 86400;
   this.secXY(tt, L, fa, high, g);
   ls = (g.mr + g.sr - Math.sqrt(g.x * g.x + g.y * g.y)) / g.sr / 2;
   if (ls > maxsf) maxsf = ls, maxjd = tt;
  }
  jd = maxjd;

**Comment by qaiu** [comment]
这段逻辑是5.10js版本新增的，已和js版本同步
