### ISSUE TITLE
不影响计算

### ISSUE THREAD

**Issue by mm-longcheng** [sxwnl/sxwnl-cpp#7]
不影响计算

_Originally posted by @qaiu in https://github.com/sxwnl/sxwnl-cpp/issues/5#issuecomment-1213328600_

**Comment by mm-longcheng** [comment]
看清楚了吗？你写的是365251.0，js版本是36525，大了十几倍，不影响计算？

**Comment by qaiu** [comment]
好的  我改一下  这么明显的错误竟然没注意到

**Comment by qaiu** [comment]
done
