### ISSUE TITLE
VS编译不通过

### ISSUE THREAD

**Issue by taynpg** [sxwnl/sxwnl-cpp#8]
`D:\download\sxwnl-cpp-master\sxwnl-cpp-master>cd build

D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build>cmake ../
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.33.31630.0
-- The CXX compiler identification is MSVC 19.33.31630.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/download/sxwnl-cpp-master/sxwnl-cpp-master/build

D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build>`

这里是能够正常的生成工程文件。但是编译不通过。

D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build>cmake --build .
MSBuild version 17.3.1+2badb37d1 for .NET Framework
  Checking Build System
  Building Custom Rule D:/download/sxwnl-cpp-master/sxwnl-cpp-master/CMakeLists.txt
  test.cpp
D:\download\sxwnl-cpp-master\sxwnl-cpp-master\test\test.cpp(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失 [D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build\te
st0.vcxproj]
D:\download\sxwnl-cpp-master\sxwnl-cpp-master\test\../tool.h(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失 [D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build\t
est0.vcxproj]
报的错误有很多，我复制了一小部分。
D:\download\sxwnl-cpp-master\sxwnl-cpp-master\lunar\lunar_ssq.cpp(255,14): error C2655: “_SSQ::leap”: 当前范围内的定义或重新声明非法 [D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build\test1.vcxproj]
D:\download\sxwnl-cpp-master\sxwnl-cpp-master\lunar\lunar_ssq.h(20): message : 参见“_SSQ::leap”的声明 [D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build\test1.vcxproj]
D:\download\sxwnl-cpp-master\sxwnl-cpp-master\lunar\lunar_ssq.cpp(256,35): error C2655: “_SSQ::ym”: 当前范围内的定义或重新声明非法 [D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build\test1.vcxproj]
D:\download\sxwnl-cpp-master\sxwnl-cpp-master\lunar\lunar_ssq.h(21): message : 参见“_SSQ::ym”的声明 [D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build\test1.vcxproj]
D:\download\sxwnl-cpp-master\sxwnl-cpp-master\lunar\lunar_ssq.cpp(257,16): error C2655: “_SSQ::ZQ”: 当前范围内的定义或重新声明非法 [D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build\test1.vcxproj]
D:\download\sxwnl-cpp-master\sxwnl-cpp-master\lunar\lunar_ssq.h(22): message : 参见“_SSQ::ZQ”的声明 [D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build\test1.vcxproj]
D:\download\sxwnl-cpp-master\sxwnl-cpp-master\lunar\lunar_ssq.cpp(258,15): error C2655: “_SSQ::pe”: 当前范围内的定义或重新声明非法 [D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build\test1.vcxproj]
D:\download\sxwnl-cpp-master\sxwnl-cpp-master\lunar\lunar_ssq.h(23): message : 参见“_SSQ::pe”的声明 [D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build\test1.vcxproj]
D:\download\sxwnl-cpp-master\sxwnl-cpp-master\lunar\lunar_ssq.cpp(260,11): error C2601: “_SSQ::calcY”: 本地函数定义是非法的 [D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build\test1.vcxproj]
D:\download\sxwnl-cpp-master\sxwnl-cpp-master\lunar\lunar_ssq.cpp(238): message : 此行有一个“{”没有匹配项 [D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build\test1.vcxproj]
D:\download\sxwnl-cpp-master\sxwnl-cpp-master\lunar\lunar_ssq.cpp(329,27): error C2001: 常量中有换行符 [D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build\test1.vcxproj]
D:\download\sxwnl-cpp-master\sxwnl-cpp-master\lunar\lunar_ssq.cpp(270): fatal  error C1075: “{”: 未找到匹配令牌 [D:\download\sxwnl-cpp-master\sxwnl-cpp-master\build\test1.vcxproj]
  tool.cpp

**Comment by qaiu** [comment]
感谢您提出的问题.
Windows平台仅测试过基于MinGW的VSCode和Cygwin, 所以Visual Studio编译可能还存在一些问题, 可能要过段时间补充修改一下...
实际上Cmake文件可以忽略, 自己写, 因为源码结构并不复杂 完全可以和现有的Cpp项目结合

**Comment by taynpg** [comment]
> 感谢您提出的问题. Windows平台仅测试过基于MinGW的VSCode和Cygwin, 所以Visual Studio编译可能还存在一些问题, 可能要过段时间补充修改一下... 实际上Cmake文件可以忽略, 自己写, 因为源码结构并不复杂 完全可以和现有的Cpp项目结合

好的，谢谢。

**Comment by qaiu** [comment]
已适配msvc编译，需要自行解决编码问题
